version: "3"

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: aleksander
      ME_CONFIG_BASICAUTH_PASSWORD: 123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo-container

    image: mongo:5

    restart: always

    volumes:
      - ./data:/data/db

    ports:
      - "27017:27017"
    
    networks:
      - mongo-compose-network

  api:
    container_name: api-container

    image: node:18
    working_dir: /usr/src/clean-node-api
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api

    restart: always

    command: bash -c "yarn install --only=prod && yarn debug"

    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json

    ports:
      - "5050:5050"
      - "9222:9222"

    links:
      - mongo

    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge
